name: big-bear-jlesage-handbrake # Name of the CasaOS application
services:
  big-bear-jlesage-handbrake:
    container_name: big-bear-jlesage-handbrake # Name of the Docker container
    image: jlesage/handbrake:v25.09.2 # Docker image for the Handbrake
    ports:
      - "5800:5800" # Expose port 5800 for VNC access
    environment:
      - VNC_PASSWORD=casaos # Set the VNC password to 'casaos'
    volumes:
      - jlesage-handbrake_config:/config
      - jlesage-handbrake_storage:/storage
      - jlesage-handbrake_watch:/watch
      - jlesage-handbrake_output:/output
volumes:
  jlesage-handbrake_config: {}
  jlesage-handbrake_storage: {}
  jlesage-handbrake_watch: {}
  jlesage-handbrake_output: {}
