# Configuration for big-bear-codex-docs setup
name: big-bear-codex-docs
# Service definitions for the big-bear-codex-docs application
services:
  app:
    image: ghcr.io/codex-team/codex.docs:v2.2
    ports:
      - "3000:3000"
    volumes:
      - codex-docs_uploads:/usr/src/app/uploads
      - codex-docs_db:/usr/src/app/db
      - codex-docs_codex_docs_config.local.yaml:/usr/src/app/docs-config.yaml
volumes:
  codex-docs_uploads: {}
  codex-docs_db: {}
  codex-docs_codex_docs_config.local.yaml: {}
