services:
  app:
    image: linuxserver/freecad:1.1.4@sha256:79e4344533aa28a03799cb1a36376f17ffee98c78890ef78d8297908eed301e8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freecad/config
        target: /config
