services:
  app:
    image: linuxserver/pairdrop:1.11.2@sha256:5f4504b22a75ed20606beeb1700a9324f647c480a4ccdfce100ba033c481ac15
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RATE_LIMIT: ''
      WS_FALLBACK: ''
      RTC_CONFIG: ''
      DEBUG_MODE: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pairdrop/config
        target: /config
