services:
  app:
    image: linuxserver/modrinth:0.21.9@sha256:091374a836e68847b4ecd7ed5d7875ded4572ba5c5bb3e5311691bc11e95a2dd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/modrinth/config
        target: /config
